#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox



  
# fcitx5 aka japanese keyboard
exec-once = fcitx5 &

# hyprpolkitagent
exec-once = systemctl --user start hyprpolkitagent

# Clipboard or cclip
# exec-once = copyq --start-server

# mako
exec-once = mako &

# waybar
exec-once = waybar

# Syncthing
# exec-once = syncthing
